### PR TITLE
Created Glowing Icon for hype.pass

### PR DESCRIPTION
**Pull request by Aryan9059**
Issue: #64 Glowing Icon

Added Glow Icon for hype.pass

### CODE REVIEW

**Comment by Aryan9059** [comment]
Issue: #92 Graph Quest

Added Graph

**Comment by aashutoshgupta15** [comment]
@Aryan9059 improve the graph task

**Comment by Aryan9059** [comment]
Okay sir

**Comment by aashutoshgupta15** [comment]
@Aryan9059 try to make graph with details, not just a line and gradient

**Comment by Aryan9059** [comment]
Sure sir.

**Pull request merged**
